from tkinter import *
window=Tk()
window.title("Simple Calculator")
i=Entry(window,borderwidth=10)
i.pack()
def mClick():
    l1=Label(window,text=i.get())
    l1.pack()
myButton1=Button(window,text="1",command=mClick).grid(row=0,column=0)
myButton2=Button(window,text="2",command=mClick).grid(row=0,column=1)
myButton3=Button(window,text="3",command=mClick).grid(row=0,column=2)
myButton4=Button(window,text="4",command=mClick).grid(row=1,column=0)
myButton5=Button(window,text="5",command=mClick).grid(row=1,column=1)
myButton6=Button(window,text="6",command=mClick).grid(row=1,column=2)
myButton7=Button(window,text="7",command=mClick).grid(row=2,column=0)
myButton8=Button(window,text="8",command=mClick).grid(row=2,column=1)
myButton9=Button(window,text="9",command=mClick).grid(row=2,column=2)
myButton1.pack()
myButton2.pack()
myButton3.pack()
myButton4.pack()
myButton5.pack()
myButton6.pack()
myButton7.pack()
myButton8.pack()
myButton9.pack()
window.mainloop()
